---
galaxy_info:
  role_name: unbound_docker
  author: your_name
  description: Run Unbound DNS resolver in a Docker container using Docker Compose v2.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: ["all"]
    - name: Ubuntu
      versions: ["all"]
    - name: EL
      versions: ["all"]

dependencies: []
